version: '3'

services:
  db:
    image: mysql:5.7.17
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mydb:/var/lib/postgresql/data
    networks:
      - default

  firendcircleapi:
    image: firendcircleapi
    build:
      context: .
      dockerfile: FriendCircleAPI/Dockerfile
    links:
      - db:db
    ports:
      - 8080:80
    restart: always
volumes:
  mydb: